#!/bin/bash

chmod 770 /etc/service/ssl-when-changed/supervise
chown box:box -R /etc/service/ssl-when-changed/supervise

cd /etc/stealthbox/ssl
exec setuser box when-changed *.key *.crt -c "service nginx reload"