FROM ubuntu:26.04

ARG DEBIAN_FRONTEND=noninteractive

RUN mkdir -p /app/Lidarr && mkdir -p /tmp/Lidarr && \
apt-get update && \
apt-get install -y --no-install-recommends ca-certificates libicu78 libsqlite3-0 curl && \
curl -o /tmp/Lidarr/Lidarr.tar.gz -L "https://lidarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64" && \
tar zxf /tmp/Lidarr/Lidarr.tar.gz -C /app/Lidarr --strip-components=1 && rm -rf /tmp/Lidarr* && \
apt-get purge -y curl && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /config && mkdir -p /data && chown -R nobody:nogroup /app /config /data
USER nobody

VOLUME /config /data

EXPOSE 8686

ENV XDG_CONFIG_HOME="/config"
WORKDIR /app/Lidarr

ENTRYPOINT ["/app/Lidarr/Lidarr"]
