#!/bin/bash

chmod 770 /etc/service/deluge-web/supervise
chown box:box -R /etc/service/deluge-web/supervise

sv start deluge || exit 1

exec setuser box deluge-web -c /home/box/deluge -p 8112 --no-ssl