#!/bin/bash

chmod 770 /etc/service/flexget/supervise
chown box:box -R /etc/service/flexget

cd /home/box/flexget
source /opt/flexget/bin/activate
exec setuser box /opt/flexget/bin/flexget daemon start