FROM ubuntu:26.04

ARG DEBIAN_FRONTEND=noninteractive

ENV SONARR_BRANCH="main"

RUN mkdir -p /app/Sonarr && mkdir -p /tmp/Sonarr && \
apt-get update && \
apt-get install -y --no-install-recommends ca-certificates libicu78 libsqlite3-0 curl && \
curl -o /tmp/Sonarr/Sonarr.tar.gz -L "https://services.sonarr.tv/v1/download/${SONARR_BRANCH}/latest?version=4&os=linux&arch=x64" && \
tar zxf /tmp/Sonarr/Sonarr.tar.gz -C /app/Sonarr --strip-components=1 && rm -rf /tmp/Sonarr* && \
apt-get purge -y curl && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /config && mkdir -p /data && chown -R nobody:nogroup /app /config /data
USER nobody

VOLUME /config /data

EXPOSE 8989

ENV XDG_CONFIG_HOME="/config"
WORKDIR /app/Sonarr

ENTRYPOINT ["/app/Sonarr/Sonarr"]
